import { FormatCode, DIM as D } from "con-utils/general";
let LOG_ENABLED = false;
export const SET_VERBOSE = (value: boolean) => LOG_ENABLED = value;
const rgb = FormatCode.createForegroundRGB;
const INFO_CODE = rgb(80, 175, 199);
const WARN_CODE = rgb(199, 133, 80);
const ERROR_CODE = rgb(199, 80, 96);
const E = ERROR_CODE.wrap, I = INFO_CODE.wrap, W = WARN_CODE.wrap;
export const ACCENT = FormatCode.create(92, 39).wrap;
export const DIM = D.wrap;
export const OUTPUT = (raw: string | Uint8Array) => process.stderr.write(raw);
export const LOG = (string: string) => void (LOG_ENABLED ? OUTPUT(DIM(`| ` + string)) : null);
export const INFO = (string: string) => void OUTPUT(I(`| ` + string));
export const WARN = (string: string) => void OUTPUT(W(`| ` + string));
export const ERROR = (string: string) => void OUTPUT(E(`| ` + string));